/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTabs: typeof import('./../components/app-tabs/index.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    ConfigurableTable: typeof import('./../components/configurable-table/index.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    CustomDrawer: typeof import('./../components/custom-drawer/index.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FilterItem: typeof import('./../components/search/filter-item/index.vue')['default']
    FloatingConfigurator: typeof import('./../components/floating-configurator/index.vue')['default']
    GlobalSearch: typeof import('./../components/global-search/index.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSelector: typeof import('./../components/icon-selector/index.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListSearch: typeof import('./../components/search/list-search/index.vue')['default']
    LoginDialog: typeof import('./../components/login-dialog/index.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    OrgSelector: typeof import('./../components/org-selector/index.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    PageContainer: typeof import('./../components/page-container/index.vue')['default']
    PageHeader: typeof import('./../components/page-header/index.vue')['default']
    PageLoading: typeof import('./../components/page-loading/index.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchStatus: typeof import('./../components/search/search-status/index.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SmartFormField: typeof import('./../components/smart-form-field/index.vue')['default']
    SplitPane: typeof import('./../components/split-pane/index.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TableColumnSettings: typeof import('./../components/table-column-settings/index.vue')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TreeTable: typeof import('primevue/treetable')['default']
    UserProfile: typeof import('./../components/user-profile/index.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
