/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigurableTable: typeof import('./../components/configurable-table/index.vue')['default']
    CustomDrawer: typeof import('./../components/custom-drawer/index.vue')['default']
    CustomPagination: typeof import('./../components/custom-pagination/index.vue')['default']
    FilterItem: typeof import('./../components/search/filter-item/index.vue')['default']
    FloatingConfigurator: typeof import('./../components/floating-configurator/index.vue')['default']
    IconSelector: typeof import('./../components/icon-selector/index.vue')['default']
    ListSearch: typeof import('./../components/search/list-search/index.vue')['default']
    OrgSelector: typeof import('./../components/org-selector/index.vue')['default']
    PageContainer: typeof import('./../components/page-container/index.vue')['default']
    PageHeader: typeof import('./../components/page-header/index.vue')['default']
    PageLoading: typeof import('./../components/page-loading/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchStatus: typeof import('./../components/search/search-status/index.vue')['default']
    SmartFormField: typeof import('./../components/form/smart-form-field/index.vue')['default']
    TableColumnSettings: typeof import('./../components/table-column-settings/index.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UserProfile: typeof import('./../components/user-profile/index.vue')['default']
  }
}
